### ISSUE TITLE
unable to run npm install

### ISSUE THREAD

**Issue by MariusLunde** [doron2402/ais-protocol-decoding#9]
Hi i am trying to use an ais-decoder for a firebase app i am making, but firebase deploy wont finish, it says there was a problem deploying, i am sure this plugin is the reason.

could there be a problem with the build script.

Great stuff btw, i am getting it to work on local deploy, and it is working perfectly.

here is some of the error message:

Build failed: {"error": {"canonicalCode": "INVALID_ARGUMENT", "errorMessage": "`npm_install` had stderr output:\nnode-pre-gyp WARN Using request for node-pre-gyp https download \nnode-pre-gyp WARN Using request for node-pre-gyp https download \nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 2\nnpm ERR! ais-decoder-ts@1.2.2 build: `rm -rf ./dist && tsc`\nnpm ERR! Exit status 2\nnpm ERR! \nnpm ERR! Failed at the ais-decoder-ts@1.2.2 build script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!

i am running node -v 8.16.1 and npm -v 6.4.1

**Comment by doron2402** [comment]
hey @MariusLunde I'm working on publishing a new version that supports node 8.16.2
stay tuned

**Comment by doron2402** [comment]
@MariusLunde try to install version 2.0.0
